// <auto-generated />
using System;
using Blueverse.MarineSafety.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blueverse.MarineSafety.Migrations
{
    [DbContext(typeof(MarineSafetyDbContext))]
    [Migration("20261005174622_SafetyProfileReviewAndAssessmentEvidence")]
    partial class SafetyProfileReviewAndAssessmentEvidence
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blueverse.MarineSafety.Models.ConditionSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ForecastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FreshnessStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 5)
                        .HasColumnType("numeric(8,5)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 5)
                        .HasColumnType("numeric(9,5)");

                    b.PrimitiveCollection<string[]>("MissingFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("Rain")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("RetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<decimal?>("SwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("WaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("RetrievedAt");

                    b.HasIndex("Latitude", "Longitude", "ForecastTime");

                    b.HasIndex("Latitude", "Longitude", "RetrievedAt");

                    b.ToTable("ConditionSnapshots");
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.MarineActivity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("MarineActivities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333301"),
                            ActivityType = "Surfing",
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Surfing"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333302"),
                            ActivityType = "Snorkeling",
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Snorkeling"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333303"),
                            ActivityType = "Diving",
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Scuba Diving"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333304"),
                            ActivityType = "BoatTour",
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Whale and Dolphin Watching"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333305"),
                            ActivityType = "BoatTour",
                            CreatedAt = new DateTime(2026, 9, 26, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Coastal Boat Tour"
                        });
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.SafetyProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("CautionSwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CautionWaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CautionWindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("CreatedByUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("EffectiveFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<decimal>("MaxSwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MaxWaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal>("MaxWindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ReviewedByUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("SwellCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SwellCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .HasColumnType("integer");

                    b.Property<string>("WaveCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WaveCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<string>("WindCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WindCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.HasKey("Id");

                    b.HasIndex("ActivityId", "IsActive")
                        .IsUnique()
                        .HasFilter("\"IsActive\"");

                    b.HasIndex("ActivityId", "Version")
                        .IsUnique();

                    b.ToTable("SafetyProfiles", null, t =>
                        {
                            t.HasCheckConstraint("CK_SafetyProfiles_CautionSwellHeight_BelowMax", "\"CautionSwellHeight\" IS NULL OR \"CautionSwellHeight\" < \"MaxSwellHeight\"");

                            t.HasCheckConstraint("CK_SafetyProfiles_CautionWaveHeight_BelowMax", "\"CautionWaveHeight\" IS NULL OR \"CautionWaveHeight\" < \"MaxWaveHeight\"");

                            t.HasCheckConstraint("CK_SafetyProfiles_CautionWindSpeed_BelowMax", "\"CautionWindSpeed\" IS NULL OR \"CautionWindSpeed\" < \"MaxWindSpeed\"");

                            t.HasCheckConstraint("CK_SafetyProfiles_MaxSwellHeight_Positive", "\"MaxSwellHeight\" > 0");

                            t.HasCheckConstraint("CK_SafetyProfiles_MaxWaveHeight_Positive", "\"MaxWaveHeight\" > 0");

                            t.HasCheckConstraint("CK_SafetyProfiles_MaxWindSpeed_Positive", "\"MaxWindSpeed\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.SuitabilityAssessmentRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("ActivityName")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.PrimitiveCollection<string[]>("CautionFactors")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<decimal?>("CautionSwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CautionWaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("CautionWindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.PrimitiveCollection<string[]>("ConditionMissingFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<DateTime?>("ConditionRetrievedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ConditionSnapshotId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("EvaluatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EvidenceCompleteness")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasDefaultValue("LEGACY_INCOMPLETE");

                    b.Property<DateTime?>("ForecastTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FreshnessStatus")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<decimal>("Latitude")
                        .HasPrecision(8, 5)
                        .HasColumnType("numeric(8,5)");

                    b.Property<decimal>("Longitude")
                        .HasPrecision(9, 5)
                        .HasColumnType("numeric(9,5)");

                    b.Property<decimal?>("MaxSwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MaxWaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("MaxWindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.PrimitiveCollection<string[]>("MissingFields")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<int>("ProfileVersion")
                        .HasColumnType("integer");

                    b.Property<decimal?>("Rain")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.Property<DateTime>("RequestedTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("SafetyProfileId")
                        .HasColumnType("uuid");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SwellCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("SwellCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("SwellHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.PrimitiveCollection<string[]>("Violations")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("WaveCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WaveCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("WaveHeight")
                        .HasPrecision(5, 2)
                        .HasColumnType("numeric(5,2)");

                    b.Property<int?>("WeatherCode")
                        .HasColumnType("integer");

                    b.Property<string>("WindCriteriaRationale")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("WindCriteriaSource")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)");

                    b.Property<decimal?>("WindSpeed")
                        .HasPrecision(6, 2)
                        .HasColumnType("numeric(6,2)");

                    b.HasKey("Id");

                    b.HasIndex("EvaluatedAt");

                    b.HasIndex("ActivityId", "RequestedTime");

                    b.ToTable("SuitabilityAssessments");
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.SafetyProfile", b =>
                {
                    b.HasOne("Blueverse.MarineSafety.Models.MarineActivity", "Activity")
                        .WithMany("SafetyProfiles")
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.SuitabilityAssessmentRecord", b =>
                {
                    b.HasOne("Blueverse.MarineSafety.Models.MarineActivity", "Activity")
                        .WithMany()
                        .HasForeignKey("ActivityId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Activity");
                });

            modelBuilder.Entity("Blueverse.MarineSafety.Models.MarineActivity", b =>
                {
                    b.Navigation("SafetyProfiles");
                });
#pragma warning restore 612, 618
        }
    }
}
