// <auto-generated />
using System;
using Blueverse.CoastalPlanner.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blueverse.CoastalPlanner.Data.Migrations
{
    [DbContext(typeof(CoastalPlannerDbContext))]
    [Migration("20260927135138_InitialCoastalPlannerSchema")]
    partial class InitialCoastalPlannerSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("coastal_planner")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.BiodiversityPredictionCache", b =>
                {
                    b.Property<Guid>("PredictionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiresAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("InferenceTimestampUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Limitations")
                        .HasColumnType("text");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SpeciesDataJson")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("PredictionId");

                    b.HasIndex("ExpiresAtUtc");

                    b.HasIndex("DestinationId", "ActivityId");

                    b.ToTable("biodiversity_predictions_cache", "coastal_planner");
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.Itinerary", b =>
                {
                    b.Property<Guid>("ItineraryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("ConcurrencyVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("OwnerUserId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ItineraryId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("OwnerUserId");

                    b.ToTable("itineraries", "coastal_planner", t =>
                        {
                            t.HasCheckConstraint("CK_itineraries_date_range", "\"EndsAtUtc\" > \"StartsAtUtc\"");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.ItineraryItem", b =>
                {
                    b.Property<Guid>("ItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActivityId")
                        .HasColumnType("uuid");

                    b.Property<string>("AdvisoryNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("DestinationId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItineraryId")
                        .HasColumnType("uuid");

                    b.Property<string>("LastAvailabilityStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastOperationalStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("LastSuitabilityStatus")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<Guid?>("OfferingId")
                        .HasColumnType("uuid");

                    b.Property<int>("OrderIndex")
                        .HasColumnType("integer");

                    b.Property<DateTime>("ScheduledEndUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("ScheduledStartUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("ItemId");

                    b.HasIndex("ItineraryId", "OrderIndex")
                        .IsUnique();

                    b.ToTable("itinerary_items", "coastal_planner", t =>
                        {
                            t.HasCheckConstraint("CK_itinerary_items_date_range", "\"ScheduledEndUtc\" > \"ScheduledStartUtc\"");

                            t.HasCheckConstraint("CK_itinerary_items_order_non_negative", "\"OrderIndex\" >= 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.PlanningWorkflow", b =>
                {
                    b.Property<Guid>("WorkflowId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FailureReason")
                        .HasColumnType("text");

                    b.Property<Guid>("InitiatorUserId")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("ResultSummary")
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("WorkflowType")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.HasKey("WorkflowId");

                    b.HasIndex("CreatedAtUtc");

                    b.HasIndex("InitiatorUserId");

                    b.HasIndex("Status");

                    b.ToTable("planning_workflows", "coastal_planner", t =>
                        {
                            t.HasCheckConstraint("CK_planning_workflows_status", "\"Status\" IN ('PENDING', 'PROCESSING', 'COMPLETED', 'FAILED')");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.RecommendationSession", b =>
                {
                    b.Property<Guid>("RecommendationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CandidatesJson")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("DurationHours")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ExcludedCandidatesCount")
                        .HasColumnType("integer");

                    b.Property<string>("ExperienceLevel")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<bool>("IncludeBiodiversityContext")
                        .HasColumnType("boolean");

                    b.Property<DateTime>("StartsAtUtc")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TargetDestinationId")
                        .HasColumnType("uuid");

                    b.Property<string>("UncertaintyNotesJson")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.HasKey("RecommendationId");

                    b.HasIndex("UserId");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.ToTable("recommendations", "coastal_planner", t =>
                        {
                            t.HasCheckConstraint("CK_recommendations_date_range", "\"EndsAtUtc\" > \"StartsAtUtc\"");

                            t.HasCheckConstraint("CK_recommendations_duration_positive", "\"DurationHours\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.ItineraryItem", b =>
                {
                    b.HasOne("Blueverse.CoastalPlanner.Data.Entities.Itinerary", "Itinerary")
                        .WithMany("Items")
                        .HasForeignKey("ItineraryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Itinerary");
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.RecommendationSession", b =>
                {
                    b.HasOne("Blueverse.CoastalPlanner.Data.Entities.PlanningWorkflow", null)
                        .WithMany()
                        .HasForeignKey("WorkflowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blueverse.CoastalPlanner.Data.Entities.Itinerary", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
