server {
    listen 80;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    server_tokens off;
    client_max_body_size 1M;

    error_page 404 =404 /_blueverse/errors/404;
    error_page 500 502 503 504 =500 /_blueverse/errors/500;

    location = /404.html { return 308 /404; }
    location = /500.html { return 308 /500; }

    gzip on;
    gzip_types text/plain text/css application/json application/javascript text/xml application/xml application/xml+rss text/javascript;
    gzip_min_length 256;

    location = /health {
        access_log off;
        add_header Content-Type text/plain;
        return 200 "healthy\n";
    }

    location = /_blueverse/errors/404 {
        internal;
        alias /usr/share/nginx/html/404.html;
    }

    location = /_blueverse/errors/500 {
        internal;
        alias /usr/share/nginx/html/500.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}
