// <auto-generated />
using System;
using Blueverse.CoastalOperations.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Blueverse.CoastalOperations.Data.Migrations
{
    [DbContext(typeof(CoastalOperationsDbContext))]
    [Migration("20260927070258_CoastalOperationsIntegrity")]
    partial class CoastalOperationsIntegrity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("coastal_operations")
                .HasAnnotation("ProductVersion", "10.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.AlertDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AlertId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<int>("ExpectedVersion")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AlertId", "DecidedAt");

                    b.ToTable("AlertDecisions", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_AlertDecisions_Decision", "\"Decision\" IN ('PUBLISH','RESOLVE','EXPIRE')");

                            t.HasCheckConstraint("CK_AlertDecisions_ExpectedVersion", "\"ExpectedVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.Assessment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AiDependencyStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<string>("AiDispatchOutcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<bool>("AiDispatchRetryable")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("InitiatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Objective")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTimeOffset>("PeriodEndsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("PeriodStartsAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("SourceWorkflowId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<Guid>("WorkflowId")
                        .HasColumnType("uuid");

                    b.Property<string>("WorkflowStatus")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("WorkflowId")
                        .IsUnique();

                    b.HasIndex("InitiatedBy", "Id");

                    b.HasIndex("WorkflowStatus", "Id");

                    b.ToTable("Assessments", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_Assessments_AiDependencyStatus", "\"AiDependencyStatus\" IN ('NOT_CONNECTED','UNAVAILABLE','AVAILABLE')");

                            t.HasCheckConstraint("CK_Assessments_AiDispatchOutcome", "\"AiDispatchOutcome\" IN ('NOT_REQUESTED','NOT_STARTED','SUCCEEDED','UNAVAILABLE','INVALID_RESULT')");

                            t.HasCheckConstraint("CK_Assessments_Period", "\"PeriodEndsAt\" > \"PeriodStartsAt\"");

                            t.HasCheckConstraint("CK_Assessments_Version", "\"Version\" > 0");

                            t.HasCheckConstraint("CK_Assessments_WorkflowStatus", "\"WorkflowStatus\" IN ('SUBMITTED','PROPOSAL_READY','PENDING_APPROVAL','REVISION_REQUESTED','REJECTED','APPROVED','EXECUTED','BLOCKED','SAFE_FAILURE')");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.AssessmentProposal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ExpectedTargetStateVersion")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("ProposalVersion")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.Property<string>("ProposedState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<bool>("RequiresSeparateReviewer")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("ValidationStatus")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId", "ProposalVersion")
                        .IsUnique();

                    b.ToTable("AssessmentProposals", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_AssessmentProposals_Validity", "\"ExpiresAt\" > \"CreatedAt\" AND \"ExpiresAt\" <= \"CreatedAt\" + INTERVAL '30 minutes'");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.IdempotencyRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<string>("RequestDigest")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("ResponseBody")
                        .IsRequired()
                        .HasMaxLength(65536)
                        .HasColumnType("character varying(65536)");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ActorId", "Operation", "Key")
                        .IsUnique();

                    b.ToTable("IdempotencyRecords", "coastal_operations");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.OperationalAlert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("character varying(4000)");

                    b.Property<string>("Lifecycle")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(160)
                        .HasColumnType("character varying(160)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("ValidFrom")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset>("ValidUntil")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("Lifecycle", "Id");

                    b.HasIndex("TargetType", "TargetId", "Lifecycle");

                    b.ToTable("OperationalAlerts", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_OperationalAlerts_Lifecycle", "\"Lifecycle\" IN ('PROPOSED','ACTIVE','RESOLVED','EXPIRED','SUPERSEDED')");

                            t.HasCheckConstraint("CK_OperationalAlerts_Period", "\"ValidUntil\" > \"ValidFrom\"");

                            t.HasCheckConstraint("CK_OperationalAlerts_Severity", "\"Severity\" IN ('LOW','MODERATE','HIGH','CRITICAL')");

                            t.HasCheckConstraint("CK_OperationalAlerts_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.OperationalHistoryEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("DecisionId")
                        .HasColumnType("uuid");

                    b.Property<string>("NewState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<string>("PreviousState")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("DecisionId");

                    b.HasIndex("ProposalId");

                    b.HasIndex("TargetType", "TargetId", "Id");

                    b.ToTable("OperationalHistory", "coastal_operations");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.OperationsAuditEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(48)
                        .HasColumnType("character varying(48)");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("CorrelationId")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ResourceId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType", "ResourceId", "CreatedAt");

                    b.ToTable("OperationsAudit", "coastal_operations");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.ReviewerDecision", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ActorId")
                        .HasColumnType("uuid");

                    b.Property<string>("AppliedOperationalState")
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<int?>("AppliedOperationalStateVersion")
                        .HasColumnType("integer");

                    b.Property<Guid>("AssessmentId")
                        .HasColumnType("uuid");

                    b.Property<DateTimeOffset>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Decision")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)");

                    b.Property<int>("ExpectedTargetStateVersion")
                        .HasColumnType("integer");

                    b.Property<string>("Explanation")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProposalId")
                        .HasColumnType("uuid");

                    b.Property<int>("ProposalVersion")
                        .HasColumnType("integer");

                    b.Property<string>("WorkflowStatusAfterDecision")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId", "DecidedAt");

                    b.HasIndex("ProposalId", "ProposalVersion")
                        .IsUnique();

                    b.ToTable("ReviewerDecisions", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_ReviewerDecisions_Decision", "\"Decision\" IN ('APPROVE','REJECT','REQUEST_REVISION')");

                            t.HasCheckConstraint("CK_ReviewerDecisions_ProposalVersion", "\"ProposalVersion\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.TargetOperationalState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<Guid>("TargetId")
                        .HasColumnType("uuid");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("uuid");

                    b.Property<int>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("TargetType", "TargetId")
                        .IsUnique();

                    b.ToTable("TargetOperationalStates", "coastal_operations", t =>
                        {
                            t.HasCheckConstraint("CK_TargetOperationalStates_State", "\"State\" IN ('OPEN','CAUTION','TEMPORARILY_SUSPENDED') OR (\"TargetType\" = 'SESSION' AND \"State\" IN ('CANCELLED','COMPLETED'))");

                            t.HasCheckConstraint("CK_TargetOperationalStates_Version", "\"Version\" > 0");
                        });
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.AlertDecision", b =>
                {
                    b.HasOne("Blueverse.CoastalOperations.Domain.OperationalAlert", null)
                        .WithMany()
                        .HasForeignKey("AlertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.AssessmentProposal", b =>
                {
                    b.HasOne("Blueverse.CoastalOperations.Domain.Assessment", "Assessment")
                        .WithMany("Proposals")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.OperationalAlert", b =>
                {
                    b.HasOne("Blueverse.CoastalOperations.Domain.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Assessment");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.OperationalHistoryEntry", b =>
                {
                    b.HasOne("Blueverse.CoastalOperations.Domain.Assessment", null)
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blueverse.CoastalOperations.Domain.ReviewerDecision", null)
                        .WithMany()
                        .HasForeignKey("DecisionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Blueverse.CoastalOperations.Domain.AssessmentProposal", null)
                        .WithMany()
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.ReviewerDecision", b =>
                {
                    b.HasOne("Blueverse.CoastalOperations.Domain.Assessment", "Assessment")
                        .WithMany("Decisions")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Blueverse.CoastalOperations.Domain.AssessmentProposal", "Proposal")
                        .WithMany("Decisions")
                        .HasForeignKey("ProposalId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Proposal");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.Assessment", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Proposals");
                });

            modelBuilder.Entity("Blueverse.CoastalOperations.Domain.AssessmentProposal", b =>
                {
                    b.Navigation("Decisions");
                });
#pragma warning restore 612, 618
        }
    }
}
